# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "geerlingguy/ubuntu1804"
    config.ssh.insert_key = false

    config.vm.provider :virtualbox do |v|
      v.memory = 2048
      v.cpus = 2
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end
  
    # Application server1 
    config.vm.define "logs" do |logs|
      logs.vm.hostname = "logs.test"
      logs.vm.network "private_network", ip: "192.168.9.90"

      logs.vm.provision :ansible do |ansible|
        ansible.compatibility_mode = "2.0"
        ansible.playbook = "playbook.yml"
        ansible.inventory_path = "inventory"
        ansible.become = true
      end
    end
  end
  